name = "eventsourcing_glyn"
version = "1.0.0"

description = "A distributed event sourcing library that enhances existing event stores with Glyn PubSub and Registry capabilities for distributed query actors, event broadcasting, and fault-tolerant command routing"
licences = ["MIT"]
repository = { type = "github", user = "renatillas", repo = "eventsourcing_glyn" }

[dependencies]
gleam_stdlib = ">= 0.52.0 and < 2.0.0"
gleam_otp = ">= 1.1.0 and < 2.0.0"
gleam_erlang = ">= 1.3.0 and < 2.0.0"
eventsourcing = ">= 9.0.0 and < 10.0.0"
glyn = ">= 2.0.0 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.2.0 and < 2.0.0"
gleam_json = ">= 3.0.2 and < 4.0.0"
